### ISSUE TITLE
HSTX pins not available

### ISSUE THREAD

**Issue by leo60228** [sparkfun/SparkFun_Pro_Micro_RP2350#1]
The 8 HSTX pins are not included in the pinout, so the new HSTX functionality in the RP2350 cannot be used.

This is despite the HSTX peripheral being mentioned in the documentation, without a caveat that it isn't usable on this board: https://docs.sparkfun.com/SparkFun_Pro_Micro_RP2350/hardware_overview/#raspberry-pi-rp2350

**Comment by sfe-SparkFro** [comment]
Thanks for pointing this out! We've updated that with a mention that it's not available on the Pro Micro.
