### ISSUE TITLE
Please add example to restore shipping configuration

### ISSUE THREAD

**Issue by vruumllc** [sparkfun/SparkFun_Pro_Micro_RP2350#3]
Hi,
Could you please add the program that ships with the Pro_Micro_RP2350 to the examples (it cycles through all the neopixel colors).
Thanks

**Comment by sfe-SparkFro** [comment]
Hi there, just pushed the compiled UF2 file for you. It's just a derivate of this example: https://github.com/raspberrypi/pico-examples/tree/master/pio/ws2812

**Comment by vruumllc** [comment]
Thanks!

**Comment by znmeb** [comment]
Where is the source for that? I can add it to my development environment. I have a script that builds all the examples for all the boards I have, including the SparkFun Pro Micro RP2350.
